### ISSUE TITLE
Documentar nueva topologia de la pipeline multistream

### ISSUE THREAD

**Issue by pcastelln** [alercebroker/kubernetes_pipeline#71]
Definir vocabulario -> glosario.

Pasos secuenciales de pipeline.

Idea general de qué hace cada paso.

Esquemas de entrada y salida para la pipeline.

Para que survey vale actualmente cada paso.

**Comment by AlxEnashi** [comment]
Me imagino el indice del documento:

1 - Glosario
2 - Esquema de orden de steps (sin nombres de topicos)
3 - Esquema de ordend e steps (con nombres de tipicos, para team ingenieria)
4 - Documentacion de cada step

Documentacion de cada step contiene:
- Nombre del step
- Proposito del step
- Esquema de entrada
- Esquema de salida
- Consideraciones sobre survey (de haber)
