### ISSUE TITLE
Añadir profiling Pyroscope en steps objetivo

### ISSUE THREAD

**Issue by pgallardor** [alercebroker/kubernetes_pipeline#94]
- [x] Sorting Hat
- [x] Scribe
- [x] Lightcurve

**Comment by edipizarro** [comment]
✅
- [Updated configmap](https://github.com/alercebroker/kubernetes_pipeline/commit/1c115f8a5d252fb23d0a5cb32b157ca1ccd08e68) so use of `USE_PROFILING` and `PYROSCOPE_SERVER` is consistent.
