### ISSUE TITLE
Deployment Balto

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/kubernetes_pipeline#97]

**Comment by edipizarro** [comment]
[Updated chart lc classifier step](https://github.com/alercebroker/kubernetes_pipeline/commit/ddd4f838cc51407902e46796dd08a74ebf52e0c7)

**Comment by dirodriguezm** [comment]
Revisado y abierto nuevo PR con una corrección https://github.com/alercebroker/kubernetes_pipeline/issues/98
